### ISSUE TITLE
Image is not being sent to trello

### ISSUE THREAD

**Issue by assafza** [fredo-ai/Fredo-Public#192] opened 2022-07-05 09:36 UTC
I was able to send the image through regular email.
But through the bot it wasn't passing. only the text of the image.

We should:
1. send the text of the image (if it exist) as the subject
2. Send the image as the body of the mail

**Comment by JerryVDP** [comment] 2022-07-05 10:10
@assafza 
Only Email and Workflowy responders support media files.
Not a bug.
Let's close it and add this as a feature if you want for a future sprint.

**Closed** 2022-07-31 09:56 UTC
