### ISSUE TITLE
Create contact person when user send phone number

### ISSUE THREAD

**Issue by assafza** [fredo-ai/Fredo-Public#237] opened 2022-08-17 08:17 UTC
When a user sends phone number system should identify it and respond to the user with a link to open the whatsapp chat link directly to this user.

**Comment by liatzionimorad** [comment] 2022-08-21 12:07
original number : 972556825268
https://wa.me/972556825268

Platform should save the number
Fredo should return link

**Comment by liatzionimorad** [comment] 2022-08-23 13:07
This is my view:
1. should work like transcribe - even before connecting to a platform , if user sends a number it should return the link.
2.  return error in case of less than 12 figures ( can be 13 with the 0)
3. can also except +972-55677777 

After platform was chosen:
should transfer to a link only if no text before or after
should keep number in chose platform as well

**Comment by assafza** [comment] 2022-08-30 21:19
Issues:
1. if a user send text including a number it should not activate this feature but rather send it regularly as an item - see example of this:
<img width="646" alt="Screen Shot 2022-08-31 at 0 18 38" src="https://user-images.githubusercontent.com/25544824/187545126-9b4d87a1-d5f6-4bdb-9f12-d507132620d9.png">

**Comment by JerryVDP** [comment] 2022-08-31 08:54
@assafza 
1. is a duplicate of #241 
2. Ok
3. Ok
4. I don't see any option to get that info

**Closed** 2022-09-11 11:15 UTC
Labels: priority-1, starter-task
